import { csvField, fmt } from "./format.js";
const HEADERS = [
    "granularity",
    "date",
    "time",
    "period",
    "weather_kind",
    "temp_min_c",
    "temp_max_c",
    "temperature_c",
    "humidity_mean_pct",
    "humidity_pct",
    "humidity_calculated",
    "precip_mm",
    "rain_mm",
    "showers_mm",
    "snow_cm",
    "cloud_mean_pct",
    "cloud_pct",
    "cloud_low_pct",
    "cloud_mid_pct",
    "cloud_high_pct",
    "dew_point_c",
    "wind_max_kt",
    "wind_speed_kt",
    "gust_kt",
    "wind_dir_deg",
    "weather_code",
    "visibility_m",
    "swell_height_m",
    "swell_period_s",
    "swell_dir_deg",
    "wave_height_m",
    "wave_period_s",
    "wave_dir_deg",
    "wind_wave_height_m",
    "marine_kind",
    "conditions",
    "notes",
];
function cell(value, digits) {
    return fmt(value, digits);
}
function dailyValues(row) {
    return [
        "daily",
        row.date,
        "",
        row.period,
        row.weatherKind,
        cell(row.tempMin, 1),
        cell(row.tempMax, 1),
        "",
        cell(row.humidityMean, 0),
        "",
        row.humidityCalculated ? "yes" : "no",
        cell(row.precipMm, 1),
        cell(row.rainMm, 1),
        cell(row.showersMm, 1),
        cell(row.snowCm, 1),
        cell(row.cloudMean, 0),
        "",
        "",
        "",
        "",
        "",
        cell(row.windMaxKt, 1),
        "",
        cell(row.gustKt, 1),
        cell(row.windDirDeg, 0),
        row.weatherCode === null ? "Unavailable" : String(row.weatherCode),
        "",
        cell(row.swellM, 2),
        cell(row.swellPeriodS, 1),
        cell(row.swellDirDeg, 0),
        cell(row.waveM, 2),
        cell(row.wavePeriodS, 1),
        cell(row.waveDirDeg, 0),
        cell(row.windWaveM, 2),
        row.marineKind,
        row.conditions.length ? row.conditions.join(" | ") : "none flagged",
        `${row.sourceDetail} ${row.marineNote}`.trim(),
    ];
}
function hourlyValues(row) {
    return [
        "hourly",
        row.date,
        row.time,
        "",
        "forecast-api-hourly",
        "",
        "",
        cell(row.tempC, 1),
        "",
        cell(row.humidityPct, 0),
        "",
        cell(row.precipMm, 2),
        cell(row.rainMm, 2),
        "",
        "",
        "",
        cell(row.cloudPct, 0),
        cell(row.cloudLowPct, 0),
        cell(row.cloudMidPct, 0),
        cell(row.cloudHighPct, 0),
        cell(row.dewPointC, 1),
        "",
        cell(row.windKt, 1),
        cell(row.gustKt, 1),
        cell(row.windDirDeg, 0),
        row.weatherCode === null ? "Unavailable" : String(row.weatherCode),
        cell(row.visibilityM, 0),
        cell(row.swellM, 2),
        cell(row.swellPeriodS, 1),
        cell(row.swellDirDeg, 0),
        cell(row.waveM, 2),
        cell(row.wavePeriodS, 1),
        cell(row.waveDirDeg, 0),
        "",
        "",
        "",
        "Hourly values come from the Forecast API and, when present, the Marine API. They are not relabeled as reanalysis.",
    ];
}
export function exportBasename(snapshot) {
    const lat = snapshot.query.lat.toFixed(4);
    const lon = snapshot.query.lon.toFixed(4);
    return `weathermeter_${lat}_${lon}_${snapshot.today}`;
}
export function toCsv(snapshot, stale) {
    const grid = snapshot.weatherGrid;
    const marine = snapshot.marineGrid;
    const comments = [
        "# Rhuanssauro Tech Inc — a datacenter in the jungle",
        "# WeatherMeter personal export",
        "# Weather data by Open-Meteo.com — https://open-meteo.com/ — CC BY 4.0 https://open-meteo.com/en/licence",
        `# name: ${snapshot.query.name || "unnamed site"}`,
        `# requested_latitude: ${snapshot.query.lat}`,
        `# requested_longitude: ${snapshot.query.lon}`,
        `# site_class: ${snapshot.query.site}`,
        `# timezone: ${snapshot.query.timezone}`,
        `# today: ${snapshot.today}`,
        `# fetched_at: ${snapshot.fetchedAt}`,
        `# stale: ${stale ? "yes" : "no"}`,
        `# weather_grid_latitude: ${grid ? grid.lat : "Unavailable"}`,
        `# weather_grid_longitude: ${grid ? grid.lon : "Unavailable"}`,
        `# weather_grid_elevation_m: ${grid && grid.elevation !== null ? grid.elevation : "Unavailable"}`,
        `# marine_grid_latitude: ${marine ? marine.lat : "Unavailable"}`,
        `# marine_grid_longitude: ${marine ? marine.lon : "Unavailable"}`,
        `# marine_error: ${snapshot.marineError ?? ""}`,
        `# archive_error: ${snapshot.archiveError ?? ""}`,
        `# marine_forecast_days_accepted: ${snapshot.marineForecastDays ?? "Unavailable"}`,
        `# weather_url: ${snapshot.weatherUrl}`,
        `# marine_url: ${snapshot.marineUrl}`,
        `# archive_url: ${snapshot.archiveUrl}`,
        "# Units are in the column names. Unavailable means the source returned no value. Values are not interpolated.",
        "# This file is a weather and sea-state view. It is not a link budget, a modem-margin result, or a navigation product.",
    ];
    const lines = [HEADERS.join(",")];
    for (const day of snapshot.days)
        lines.push(dailyValues(day).map(csvField).join(","));
    for (const hour of snapshot.hours)
        lines.push(hourlyValues(hour).map(csvField).join(","));
    return `${comments.join("\n")}\n${lines.join("\n")}\n`;
}
